// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: protos/Keys.proto

package securitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyTypes int32

const (
	KeyTypes_ECDSA     KeyTypes = 0
	KeyTypes_KYBER     KeyTypes = 1
	KeyTypes_DILITHIUM KeyTypes = 2
	KeyTypes_FALCON    KeyTypes = 3
)

// Enum value maps for KeyTypes.
var (
	KeyTypes_name = map[int32]string{
		0: "ECDSA",
		1: "KYBER",
		2: "DILITHIUM",
		3: "FALCON",
	}
	KeyTypes_value = map[string]int32{
		"ECDSA":     0,
		"KYBER":     1,
		"DILITHIUM": 2,
		"FALCON":    3,
	}
)

func (x KeyTypes) Enum() *KeyTypes {
	p := new(KeyTypes)
	*p = x
	return p
}

func (x KeyTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_Keys_proto_enumTypes[0].Descriptor()
}

func (KeyTypes) Type() protoreflect.EnumType {
	return &file_protos_Keys_proto_enumTypes[0]
}

func (x KeyTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyTypes.Descriptor instead.
func (KeyTypes) EnumDescriptor() ([]byte, []int) {
	return file_protos_Keys_proto_rawDescGZIP(), []int{0}
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Public  string   `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	Type    KeyTypes `protobuf:"varint,3,opt,name=type,proto3,enum=security.KeyTypes" json:"type,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Keys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Keys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_protos_Keys_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Key) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *Key) GetType() KeyTypes {
	if x != nil {
		return x.Type
	}
	return KeyTypes_ECDSA
}

var File_protos_Keys_proto protoreflect.FileDescriptor

var file_protos_Keys_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x4b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x22, 0x5f, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e,
	0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x3b,
	0x0a, 0x08, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x43,
	0x44, 0x53, 0x41, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4b, 0x59, 0x42, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x4c, 0x49, 0x54, 0x48, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x4c, 0x43, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x67, 0x64,
	0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x77, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_Keys_proto_rawDescOnce sync.Once
	file_protos_Keys_proto_rawDescData = file_protos_Keys_proto_rawDesc
)

func file_protos_Keys_proto_rawDescGZIP() []byte {
	file_protos_Keys_proto_rawDescOnce.Do(func() {
		file_protos_Keys_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_Keys_proto_rawDescData)
	})
	return file_protos_Keys_proto_rawDescData
}

var file_protos_Keys_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_Keys_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_Keys_proto_goTypes = []interface{}{
	(KeyTypes)(0), // 0: security.KeyTypes
	(*Key)(nil),   // 1: security.Key
}
var file_protos_Keys_proto_depIdxs = []int32{
	0, // 0: security.Key.type:type_name -> security.KeyTypes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_Keys_proto_init() }
func file_protos_Keys_proto_init() {
	if File_protos_Keys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_Keys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_Keys_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_Keys_proto_goTypes,
		DependencyIndexes: file_protos_Keys_proto_depIdxs,
		EnumInfos:         file_protos_Keys_proto_enumTypes,
		MessageInfos:      file_protos_Keys_proto_msgTypes,
	}.Build()
	File_protos_Keys_proto = out.File
	file_protos_Keys_proto_rawDesc = nil
	file_protos_Keys_proto_goTypes = nil
	file_protos_Keys_proto_depIdxs = nil
}
